version: '3.9'

services:
  server:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    image: 'postgres'
    ports:
      - '4321:5432'
    environment:
      POSTGRES_PASSWORD: 'mypassword123'
      POSTGRES_USER: 'testUser'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
